### ISSUE TITLE
build researcher function needs to be more robust

### ISSUE THREAD

**Issue by ihardy** [WRLC/orcid_task_service#17]
review each field to check if required or not, decide exactly what to do if the field is not present.

**Comment by dongourley** [comment]
The required fields for replacing/updating an existing MADS are:

        "identifier": {
            "u1": "...",
            "netid": "..."
        },

I think the additional fields required for creating a new MADS would probably be:

        "authority": {
            "name": {
                "family": "..."
            },
            "titleInfo": {
                "title": "..."
            }
        },

(I create the "title" from whatever name and position info is in the ORCID record so I will never give you "name" without "titleInfo")

**Comment by ihardy** [comment]
This finally came back up for Aaron. Will fix now. Error Log from Don:

```
[Mon Feb 12 14:18:49.593341 2018] [:error] [pid 9975] [client 172.27.5.18:62230] ORCID DEBUG: PUT http://ops.wrlc.org:8181/api/islandora/0000-0003-0726-7835?{"identifier":{"u1":"0000-0003-0726-7835","netid":"krebeck@wrlc.org"},"authority":{"name":{"given":"Aaron","family":"Krebeck"},"titleInfo":{"title":"Aaron Krebeck"}},"note":{"history":"Aaron Krebeck is a digital services librarian at Washington Research Library Consortium.  He specializes in Islandora digital repositories.  He was born in 1978."},"citations":"https:\\/\\/pub.orcid.org\\/v2.0\\/0000-0003-0726-7835\\/works\\/37356835"}, referer: https://dra.american.edu/orcid/?bypass=authN&state=krebeck@wrlc.org
[Mon Feb 12 14:18:49.795706 2018] [:error] [pid 9975] [client 172.27.5.18:62230] ORCID DEBUG: RESPONSE (500) Traceback (most recent call last):\n  File "app/utils/makecalls.py", line 402, in <module>\n    main()\n  File "app/utils/makecalls.py", line 348, in main\n    researcher_attrs = build_researcher_dict()\n  File "app/utils/makecalls.py", line 76, in build_researcher_dict\n    r_dict['organization'] = extract_attr(req_json['affiliation'], 'organization')\nKeyError: 'affiliation'\n, referer: https://dra.american.edu/orcid/?bypass=authN&state=krebeck@wrlc.org
[Mon Feb 12 14:18:49.795753 2018] [:error] [pid 9975] [client 172.27.5.18:62230] HTTP Response Code 500, referer: https://dra.american.edu/orcid/?bypass=authN&state=krebeck@wrlc.org
```
